{{- if .Values.serviceMonitor }}
{{- if .Values.serviceMonitor.enabled }}
apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  labels:
{{- include "prometheus-envoy.labels" . | nindent 4 }}
{{- if .Values.serviceMonitor.additionalLabels }}
{{ toYaml .Values.serviceMonitor.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.serviceMonitor.annotations }}
  annotations:
{{ toYaml .Values.serviceMonitor.annotations | indent 4 }}
{{- end }}
  name: {{ include "prometheus-envoy.fullname" . }}-svc-monitor
  namespace: {{ template "prometheus-envoy.namespace" . }}
spec:
  selector:
    {{- include "prometheus-envoy.selectorLabels" . | nindent 4 }}
  namespaceSelector:
    matchNames:
    - {{ template "prometheus-envoy.namespace" . }}
  endpoints:
{{ toYaml .Values.serviceMonitor.endpoints | indent 4 }}
{{- end }}
{{- end }}