name: CI
on: [pull_request]
env:
  CHART_NAME: "prometheus-envoy"
  CHART_PATH: "deploy/kubernetes/helm/prometheus-envoy"
jobs:
  helm-chart-test:
    runs-on: ubuntu-latest 
    name: Test Helm Chart
    strategy:
      matrix:
        kubernetes: [1.19.11, 1.20.7, 1.21.1, 1.22.0, 1.23.0]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{github.event.pull_request.head.sha}}
    - name: Setup Ephemeral Kubernetes Testing Cluster
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.11.1"    
    # Set Up Helm
    - name: Set up Helm
      uses: azure/setup-helm@v3.3
      with:
        version: v3.10.0
    # Lint
    - name: Helm Lint
      run: |
        helm lint ${CHART_PATH}
    # Dry run to ensure that manifests are generated successfully 
    - name: Dry Run Chart
      run: |
        helm install ${CHART_NAME} ${CHART_PATH} -f ${CHART_PATH}/values.yaml -n helm-chart-pipeline-test --dry-run --debug
    # package
    - name: Helm Package
      run: |
        helm package ${CHART_PATH}
    - name: Comment on PR
      uses: mshick/add-pr-comment@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: '@${{ github.actor }} Validation Successful'
        allow-repeats: false